# Generated by Django 5.1 on 2024-09-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_place_description_place_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='img_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
